services:
  groups:
    build:
      context: .
      dockerfile: web/Dockerfile
    expose:
      - 8000
    env_file:
      - .env
    environment:
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: groups.tk.sg
    volumes:
      - ./service-account-credentials.json:/app/service-account-credentials.json:ro
    networks:
      devtksg:
    restart: always

networks:
  devtksg:
    external: true
